import type { Metadata } from "next";
import "./globals.css";
import '@rainbow-me/rainbowkit/styles.css';
import '@suiet/wallet-kit/style.css';
import { Providers } from "@/providers/rainbowkit";
import NextAuthProvider from "@/providers/next-auth";
import SuietWalletProvider from "@/providers/suiet";

import Nav from "@/components/Nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <NextAuthProvider>
            <SuietWalletProvider>
              <Nav />
              {children}
            </SuietWalletProvider>
          </NextAuthProvider>
        </Providers>
      </body>
    </html>
  );
}
